import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import TokenSync from "@/components/TokenSync";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TokenSync />
        {children}
      </body>
    </html>
  );
}
